language: node_js

node_js:
  - "4"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphicsmagick

env:
  matrix:
    - CXX=g++-4.8
  global:
    - secure: "IEz1U/E9yWxOWwAOSI4PlESkmrKq84+3cVGF1AX5TptTwozvpnYFG2thbuxz2tpQN/aUjbGDsZyk82rB6RDzOqA7wC0fvLhBz7BSOV6xejzBAJZKiTHEzznf/ePi+o3TatA3FXiuy94qvYT0ha4BzE86qOD0+QCQOjnVvPt36hSdqZ7KuI4o1NxjgP35vXDfVMn7nCReJ9P5HAhS5S/rd3AuUUwXNotk/4GLEAhaROkqW1CQCuwxiyTbSr8/WYEPs4kMrPmeI3uK4ULZhnI/b8vi0aj38AGSULVAoQ04L9iGP85nBo2VQ5EylQc8TkOkRsN7KH8C7xYd4qxlEk0GQnUqbgWCs/k3YVPan7R/o7S1mmTKvo6fyMrrAslExUuDR806T5AJpqdtNSzGEEPABEr/Oz+RAOBYYn9baMFW8pKrhsDGk3WxKFOu9OENToiImq2gPu8kO6uOhZBtCdLJXHBeNOixJ08Z7M0O7bzxsMJYDotUdlZIN0nhYBC6gcNSIslRmtsyetMv5HU/noacqcBL7fG9jyoHmb4IW3mmAIg22Ks/pREXrDvh60bJfmcC8M+4wgMAk8DVCeRbUo0YOckNsaKEONI6el7vpHUy1G9yVc3kC3QyPe7BpoCHZA1eihu/cuiZb6XV6TGfedRW+vbkBodMOvK7Y+QXPE5JnYY="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

before_install:
  # Set Git config
  - git config --global user.name "meolu"
  - git config --global user.email "wushuiyong@huamanshu.com"
  - git config --global push.default simple

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/meolu/walle-web.io.git .deploy_git -v
  # Update docs.
  - git --version
  # - git remote add -f docs https://${GH_TOKEN}@github.com/meolu/doc.git
  # - git fetch docs
  # - git subtree add --prefix=source/docs/en docs/en --squash
  # - git subtree add --prefix=source/docs/zh-cn docs/zh-cn --squash
  # Install dependencies
  - mv -f walle-web.io/* source/
  - npm install --no-optional

after_script:
  - hexo generate && gulp
  - cp -rf public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force

branches:
  only:
    - master
