language: node_js

node_js:
  - "4.1"

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  # Set Git config
  - git config --global user.name "overtrue"
  - git config --global user.email "anzhengchao@gmail.com"
  - git config --global push.default simple

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/easywechat/easywechat.github.io.git .deploy_git -v
  # Update docs.
  - git --version
  - git subtree add docs --prefix=source/docs/ https://${GH_TOKEN}@github.com/easywechat/docs.git
  - git fetch docs
  - git subtree add -P zh-cn source/docs/zh-cn
  - git subtree add -P en source/docs/en
  # Install Hexo
  - npm install hexo-cli -g
  # Install dependencies
  - npm install --no-optional

after_script:
  - hexo generate && gulp
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force

branches:
  only:
    - master