language: node_js

node_js:
  - "4.1"

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  # Set Git config
  - git config --global user.name "overtrue"
  - git config --global user.email "anzhengchao@gmail.com"

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/easywechat/easywechat.github.io.git .deploy_git
  # Update docs.
  - git --version
  - git subtree add --prefix=source/docs/ git@github.com:easywechat/docs.git zh-cn
  - git subtree add --prefix=source/en/docs/ git@github.com:easywechat/docs.git en
  # Install Hexo
  - npm install hexo-cli -g
  # Install dependencies
  - npm install --no-optional

script:
  - hexo generate && gulp && hexo deploy

branches:
  only:
    - master