language: node_js

node_js:
  - "4.1"
cache:
  - apt
  - bundler
addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  # Set Git config
  - git config --global user.name "overtrue"
  - git config --global user.email "anzhengchao@gmail.com"
  - git config --global push.default simple

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/easywechat/easywechat.github.io.git .deploy_git -v
  # Update docs.
  - git --version
  - git remote add -f docs https://${GH_TOKEN}@github.com/easywechat/docs.git
  - git fetch docs
  - git subtree add --prefix=source/docs/zh-cn docs/zh-cn --squash
  - git subtree add --prefix=source/docs/en docs/en --squash
  # Install Hexo
  - npm install hexo-cli -g
  # Install dependencies
  - npm install --no-optional

after_script:
  - hexo generate && gulp
  - cp -r public/* .deploy_git/
  - cd .deploy_git
  - cp docs/zh-cn/index.html ./docs
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force

branches:
  only:
    - master